#!/usr/bin/env python2.7
# -*- mode: Python -*-
#

# Print miptable:varname for CMOR variables in the DECK
#

from dqi.walker import walk_dq, mips_of_cmv
from dqi.tools import ldq

def walkit(dq):
    ruleset = {'CMORvar': (lambda cmv, dqt, rules, dq,
                           for_side_effect=False, **junk:
                               (True if "DECK" in mips_of_cmv(cmv, dq)
                                else False))}
    return walk_dq(dq, ruleset)

if __name__ == '__main__':
    for (mtn, varmap) in walkit(ldq()).iteritems():
        for (varname, decktuple) in varmap.iteritems():
            for foundp in decktuple:
                if foundp:
                    print "{}:{}".format(mtn, varname)
