#!/usr/bin/env python2.7
# -*- mode: Python -*-
#

# Print miptable:varname for CMOR variables in the DECK
#

from dqi.walker import walk_dq, mips_of_cmv
from dqi.tools import ldq

def walkit(dq):
    return walk_dq(dq, {'CMORvar': (lambda cmv, dqt, rules, dq,
                                    for_side_effect=False, **junk:
                                        mips_of_cmv(cmv, dq))})

if __name__ == '__main__':
    for (mtn, varmap) in walkit(ldq()).iteritems():
        for (varname, mts) in varmap.iteritems():
            for mips in mts:
                if 'DECK' in mips:
                    print "{} {} {}".format(mtn, varname, ":"
                                            .join(mip for mip in mips
                                                  if mip != 'DECK'))
