#!/usr/bin/env python2.7
# -*- mode: Python -*-
#
# (C) British Crown Copyright 2016, Met Office.
# See LICENSE.md in the top directory for license details.
#

# Report on CMORvar names which occur multiple times in a mip table
#

from sys import exit
from argparse import ArgumentParser # 2.7
from dqi.util import walk_from_dqroot

def spit(walked):
    for (miptable, vartable) in sorted(walked.iteritems(), key=lambda i: i[0]):
        for (var, vals) in sorted(vartable.iteritems(), key=lambda i: i[0]):
            if len(vals) > 1:
                print "{} {} {}".format(miptable, var, len(vals))

if __name__ == '__main__':
    parser = ArgumentParser(
        description="Report on multiple-instance CMORvar names")
    parser.add_argument("dqroot", nargs='?', default=None,
                        help="dq root dir if given")
    parser.add_argument("-D", action='store_true', dest='debug',
                        help="debugging (don't suppress backtraces)")
    args = parser.parse_args()
    try:
        spit(walk_from_dqroot(args.dqroot))
    except Exception as e:
        if not args.debug:
            exit(e)
        else:
            raise
