# (C) British Crown Copyright 2016, Met Office.
# See LICENSE.md in the top directory for license details.
#

# Don't build the diagnostic-reviewers branch, or any experimental
# branch
#
branches:
  except:
    - diagnostic-reviewers
    - /experimental/

# Run unit tests on djq and dqi and sanity tests on djq
#

language: python
python: "2.7"

install:
  # Everything needs the DREQ API: get the latest tag only to speed it up
  - svn co http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags/latest CMIP6dreq/tags/latest
  # and fake up the trunk so djq is happy it's a root
  - mkdir -p CMIP6dreq/trunk
  - (cd CMIP6dreq/tags/latest && python setup.py install)
  # Sanity tests need openpyxl
  - pip install openpyxl

script:
  # Basic unit tests
  - nosetests -w djq
  - nosetests -w dqi
  # Just install and test, do not make sanity any more as there's no
  # real chance it will work
  - make -C djq install test DJQ_DQROOT=$(pwd)/CMIP6dreq
  # run djq & cci in a rudimentary way to make sure something works
  - all-requests -r CMIP6dreq | djq -r CMIP6dreq >/dev/null
  - all-requests -r CMIP6dreq | cci -s -r CMIP6dreq
