#!/usr/bin/env python
#
# Just run the walker and dump some JSON
#

from sys import stdout
from json import dump
from dqwalker import walk_dq
from rulesets import original
from dreqPy.dreq import loadDreq

dump(walk_dq(loadDreq(), ruleset=original), stdout, indent=2, sort_keys=True)
print ""
