# (C) British Crown Copyright 2016, Met Office.
# See LICENSE.md in the top directory for license details.
#

# Run all comparisons
#

PYTHON	= python

.PHONY: compare

compare:
	$(PYTHON) xlsx/xlsxcompare.py
